// mkvtool v2 build. Versions come from gradle/libs.versions.toml (single source of truth); the
// project's own version comes from gradle.properties.

// Imported rather than written out where used: inside a build script `java` names the Java plugin's
// extension, so a fully qualified `java.io.…` does not resolve to the package at all.
import java.io.IOException
import java.io.RandomAccessFile
import java.util.Locale

plugins {
    // Versions supplied by the version catalog.
    alias(libs.plugins.kotlin.jvm)
    // kapt runs picocli-codegen: it is a javac annotation processor, so KSP cannot
    // run it. picocli-codegen generates the GraalVM reflection config under
    // META-INF/native-image, consumed by the native-image build below.
    alias(libs.plugins.kotlin.kapt)
    // kotlinx.serialization is a *compiler* plugin: it generates each @Serializable
    // class's serializer at compile time, so JSON parsing needs no runtime reflection
    // and therefore no native-image reachability config.
    alias(libs.plugins.kotlin.serialization)
    // installDist provides the dev launcher; also names it via applicationName below.
    application
    // Maintained shadow fork (com.gradleup.*); the old johnrengelman fork is dead.
    // Wires shadowJar into `assemble`, so `build` produces the fat jar.
    alias(libs.plugins.shadow)
    // GraalVM native-image. Adds the `nativeCompile` task and consumes the reflection
    // config kapt/picocli-codegen emits under META-INF/native-image. Applying it costs
    // nothing on an ordinary JDK; only `nativeCompile` requires a GraalVM JDK.
    alias(libs.plugins.graalvm.native)
}

group = "org.plukh"
// version is inherited from gradle.properties.

// JDK 21 (LTS) toolchain via Gradle toolchains — compilation and test execution use
// JDK 21 regardless of the JDK that launched Gradle.
//
// Deliberately no vendor constraint. Adding one — to make this agree with the GraalVM that
// nativeCompile needs — would require every developer to install GraalVM before they could build
// the *jar*, and would stop the build outright on a Windows machine, which cannot build a native
// image at all (native-image wants MSVC). GraalVM is supplied by the environment instead; see
// docs/building.md.
kotlin {
    jvmToolchain(21)
}

application {
    mainClass.set("org.plukh.mkvtool.cli.MainKt")
    // Makes the installDist / distribution launcher be named `mkvtool` (+ .bat).
    applicationName = "mkvtool"
}

dependencies {
    implementation(libs.picocli)
    kapt(libs.picocli.codegen)
    implementation(libs.snakeyaml)
    implementation(libs.kotlinx.serialization.json)

    testImplementation(libs.kotest.runner.junit5)
    testImplementation(libs.kotest.assertions.core)
}

// Version is defined once (project.version, from gradle.properties) and surfaced to
// the runtime through a generated Kotlin source. A compiled-in `const` needs no
// classpath resource loading, so it behaves identically under installDist, the shadow
// jar, and native-image with zero resource-inclusion config — unlike a bundled
// .properties resource, which native-image would need told about explicitly.
val generateBuildInfo = tasks.register("generateBuildInfo") {
    val version = project.version.toString()
    val outputDir = layout.buildDirectory.dir("generated/buildinfo")
    inputs.property("version", version)
    outputs.dir(outputDir)
    doLast {
        val pkgDir = outputDir.get().asFile.resolve("org/plukh/mkvtool")
        pkgDir.mkdirs()
        pkgDir.resolve("BuildInfo.kt").writeText(
            """
            package org.plukh.mkvtool

            /** Build-time facts, generated by the `generateBuildInfo` Gradle task. */
            internal object BuildInfo {
                const val VERSION: String = "$version"
            }
            """.trimIndent() + "\n",
            Charsets.UTF_8,
        )
    }
}

// Passing the task provider to srcDir wires both the generated directory and the
// compileKotlin -> generateBuildInfo dependency.
kotlin.sourceSets.main {
    kotlin.srcDir(generateBuildInfo)
}

// Native binary. The two buildArgs guard the two silent native-image failure modes;
// the hidden `native-smoke` command probes both end-to-end in CI, and would fail at
// runtime if either flag were dropped:
//   -H:+AddAllCharsets  - keep every JDK charset; without it `to-utf8` loses non-default
//                         encodings (e.g. windows-1251) and Charset.forName throws.
//   -H:+IncludeAllLocales - bundle CLDR locale data; without it language display names
//                           (Русский, 日本語) come back empty.
graalvmNative {
    // Our only reachability config comes from picocli-codegen (emitted under
    // META-INF/native-image). The plugin's third-party GraalVM reachability-metadata
    // repository is unused here, and its schema demands a newer GraalVM than the last
    // GraalVM CE for JDK 21 (21.0.2, which CI's graalvm-community/21 also resolves to)
    // ships - leaving it on fails nativeCompile. Disable it.
    metadataRepository {
        enabled.set(false)
    }
    binaries {
        named("main") {
            imageName.set("mkvtool")
            mainClass.set(application.mainClass.get())
            buildArgs.add("-H:+AddAllCharsets")
            buildArgs.add("-H:+IncludeAllLocales")
            // kotlinx.serialization initializes its generated serializers at build time, which reaches
            // kotlin.DeprecationLevel (the enum behind every @Deprecated annotation) and leaves it
            // initialized while native-image's default policy still wants it at run time — the build then
            // fails outright. Marking the enum build-time settles the disagreement; it is a compile-time
            // constant holder with no state worth deferring. Without this, nativeCompile fails as soon as
            // anything @Serializable is reachable.
            buildArgs.add("--initialize-at-build-time=kotlin.DeprecationLevel")
        }
    }
}

tasks.test {
    useJUnitPlatform()
    // Two specs assert against the user documentation — the config keys it names, and the sample reports
    // it shows. Gradle cannot see that from the test classpath, so without declaring the files it treats
    // the task as up to date after a documentation-only edit and the check silently does not run. It would
    // still run in CI, where nothing is cached, which is the worst version of this: green locally, red on
    // push.
    inputs.files("docs/reference.md", "docs/config.example.yaml")
        .withPropertyName("documentationUnderTest")
        .withPathSensitivity(PathSensitivity.RELATIVE)
}

tasks.jar {
    manifest {
        attributes("Implementation-Version" to project.version)
    }
}

tasks.shadowJar {
    // Make the fat jar runnable via `java -jar`.
    manifest {
        attributes("Main-Class" to application.mainClass.get())
    }
}

// Release packaging.
//
// All of it lives here rather than as shell in the release workflow, for three reasons: one
// task writes the same archive on Windows, Linux and macOS, where shell would need a
// different zipper per host (Git Bash on the Windows runner has no `zip`); the tar entry's
// executable bit is set explicitly instead of inherited from whatever is on disk; and it can
// be run on a developer machine before anything is pushed, which is where the last round of
// CI plumbing bugs would have been caught.

// CI reads the version from here rather than parsing gradle.properties, so there is exactly
// one implementation of "what version is this" - the same project.version that names every
// archive and is compiled into BuildInfo.
tasks.register("printVersion") {
    group = "help"
    description = "Prints the project version, for scripts and CI."
    val version = project.version.toString()
    doLast { println(version) }
}

val hostIsWindows = System.getProperty("os.name").lowercase().startsWith("windows")

// The archive's platform label is *derived* from the machine running the build rather than
// passed in on the command line, so an archive cannot claim an architecture its binary does
// not have: a toolchain that handed this host the wrong JDK produces the wrong label here,
// two release legs then write the same file name, and the asset-set check downstream fails
// instead of an arm64 build shipping as x64. The vocabulary is fixed - windows/linux/macos
// crossed with x64/arm64 - because published archive URLs are what package manifests pin.
//
// Lazy, so an unmappable host fails when a release task actually runs rather than breaking
// every ordinary build on it.
val releasePlatform: String by lazy {
    val os = System.getProperty("os.name").lowercase()
    val osLabel = when {
        os.startsWith("windows") -> "windows"
        os.startsWith("mac") -> "macos"
        os.startsWith("linux") -> "linux"
        else -> error("no release platform label for os.name=$os")
    }
    val arch = System.getProperty("os.arch")
    val archLabel = when (arch) {
        "amd64", "x86_64" -> "x64"
        "aarch64", "arm64" -> "arm64"
        else -> error("no release platform label for os.arch=$arch")
    }
    "$osLabel-$archLabel"
}

// Overridable so an archive can be rebuilt around a binary that was signed after the fact,
// which happens on another machine; the default is what nativeCompile writes.
val nativeBinaryPath: String = providers.gradleProperty("nativeBinary").orNull
    ?: if (hostIsWindows) "build/native/nativeCompile/mkvtool.exe" else "build/native/nativeCompile/mkvtool"

// The archive's own readme: one template rendering all three platforms, rather than three
// near-identical files in the repository drifting apart. Deliberately not a copy of
// README.md - that file is a living front page, and a snapshot of it is stale the moment the
// branch moves past the release - while this one is nearly static.
val releaseReadme = tasks.register("releaseReadme") {
    group = "distribution"
    description = "Renders the README.txt that ships inside this platform's release archive."
    val version = project.version.toString()
    val platform = releasePlatform
    val outputDir = layout.buildDirectory.dir("release-readme")
    inputs.property("version", version)
    inputs.property("platform", platform)
    outputs.dir(outputDir)
    doLast {
        // One paragraph differs per platform: what the operating system is about to stop the
        // reader with, and the answer to it.
        val platformNote = when {
            platform.startsWith("windows") -> listOf(
                "This binary is not code-signed. Windows may therefore show a \"Windows protected",
                "your PC\" prompt the first few times it is launched from Explorer - choose More",
                "info, then Run anyway - and a browser may warn that it is not commonly",
                "downloaded. The checksums file attached to the release is how to verify it.",
            )
            platform.startsWith("macos") -> listOf(
                "macOS quarantines anything downloaded by a browser, and reports it as damaged or",
                "from an unidentified developer. Clear the attribute once, after extracting:",
                "",
                "    xattr -d com.apple.quarantine mkvtool",
            )
            // Linux gets the shared text alone.
            else -> emptyList()
        }
        val binaryName = if (platform.startsWith("windows")) "mkvtool.exe" else "mkvtool"
        val lines = listOf(
            "mkvtool $version",
            "",
            "Automates MKV workflows: muxing a season from its parts, inspecting track layouts,",
            "renaming episodes from their metadata, and the post-processing around both.",
            "",
            "Put $binaryName anywhere on your PATH and run `mkvtool --version` to check it.",
            "There is no runtime to install alongside it.",
            "",
            "MKVToolNix is required: mkvmerge is looked up on PATH, and mkvpropedit as well for",
            "the propedit command. https://mkvtoolnix.download/",
            "",
            "Commands, options and the config.yaml reference:",
            "https://github.com/vdenisov/mkvtool",
        ) + (if (platformNote.isEmpty()) emptyList() else listOf("") + platformNote) + listOf(
            "",
            "MIT licensed - the full text is in LICENSE, next to this file.",
        )
        // CRLF in the Windows archive: current Notepad reads LF, but every other Windows text
        // tool is happier with CRLF, and the choice costs one line here.
        val eol = if (platform.startsWith("windows")) "\r\n" else "\n"
        val dir = outputDir.get().asFile
        dir.mkdirs()
        dir.resolve("README.txt").writeText(lines.joinToString(eol) + eol, Charsets.UTF_8)
    }
}

// One flat archive per platform: the bare binary, LICENSE, and the generated README.txt.
//
// This deliberately does *not* depend on nativeCompile. What gets archived is the binary as
// it stands in build/native/nativeCompile, which in CI is the file the smoke probes and the
// acceptance cases just ran - a fresh compile of the same sources would be an untested one.
fun AbstractArchiveTask.configureReleaseArchive(extension: String) {
    val platform = releasePlatform
    val binary = file(nativeBinaryPath)
    group = "distribution"
    description = "Flat release archive for this platform: the native binary, LICENSE and README.txt."
    destinationDirectory.set(layout.buildDirectory.dir("release"))
    archiveFileName.set("mkvtool-${project.version}-$platform.$extension")
    from(binary) {
        // tar carries this through, which is why no install path - a manual download,
        // Homebrew, the AUR - ever needs a chmod step.
        filePermissions { unix("0755") }
        // The inner name is the one thing outside this repository depends on: it is what a
        // Scoop `bin` and a Homebrew `bin.install` point at, and what a manual installer puts
        // on PATH. Renaming rather than trusting the source name is what lets the binary be
        // taken from anywhere - a signed copy sitting in some other directory included -
        // without the archive's contract changing.
        rename { if (hostIsWindows) "mkvtool.exe" else "mkvtool" }
    }
    from(layout.projectDirectory.file("LICENSE"))
    from(releaseReadme)
    // No top-level directory: nothing is gained by nesting a single binary, and the wrapper
    // would become a strip-components line in every package manifest pointing here.
    isPreserveFileTimestamps = false
    isReproducibleFileOrder = true
    // A CopySpec skips a missing source silently, so the binary's presence is asserted rather
    // than assumed - an archive without the tool in it would otherwise upload perfectly well.
    doFirst {
        require(binary.isFile) {
            "no native binary at $binary - run nativeCompile first, or pass -PnativeBinary=<path>"
        }
    }
}

// zip on Windows (the native format there, and what Scoop and winget consume directly),
// tar.gz elsewhere, since it preserves the executable bit.
if (hostIsWindows) {
    tasks.register<Zip>("releaseArchive") { configureReleaseArchive("zip") }
} else {
    tasks.register<Tar>("releaseArchive") {
        compression = Compression.GZIP
        configureReleaseArchive("tar.gz")
    }
}

// The published jar is the shadow jar under the name the release promises. A copy rather than
// clearing shadowJar's classifier, because the thin jar the `jar` task writes already owns
// build/libs/mkvtool-<version>.jar.
tasks.register<Copy>("releaseJar") {
    group = "distribution"
    description = "The shadow jar under its release name, in build/release."
    // Read here rather than inside rename: that lambda runs at execution time, where reaching
    // for the project is deprecated and stops working in Gradle 10.
    val releaseJarName = "mkvtool-${project.version}.jar"
    from(tasks.shadowJar)
    into(layout.buildDirectory.dir("release"))
    rename { releaseJarName }
}

// The fat jar is a published artifact that no test tier runs: the acceptance harness drives
// the installDist launcher, and the native legs drive the binary. The harness needs an
// *executable* to point --app-bin at, so this generates the smallest one that satisfies it -
// every argument forwarded, the child's exit code passed through, nothing of its own printed,
// and the jar addressed relative to the script, because the harness gives each case a fresh
// working directory. JAVA_HOME is preferred because the harness pins it in the child
// environment to the JVM running the suite.
tasks.register("jarLauncher") {
    group = "verification"
    description = "A launcher that runs the shadow jar, for --app-bin in the acceptance harness."
    dependsOn(tasks.shadowJar)
    val jarName = "mkvtool-${project.version}-all.jar"
    val outputDir = layout.buildDirectory.dir("jar-launcher")
    inputs.property("jarName", jarName)
    outputs.dir(outputDir)
    doLast {
        val dir = outputDir.get().asFile
        dir.mkdirs()
        val posix = dir.resolve("mkvtool")
        posix.writeText(
            listOf(
                "#!/bin/sh",
                "# Generated by the jarLauncher Gradle task.",
                "# exec, so the jar's exit code is this script's exit code with no process between.",
                "dir=\$(dirname \"\$0\")",
                "if [ -n \"\$JAVA_HOME\" ]; then java=\"\$JAVA_HOME/bin/java\"; else java=java; fi",
                "exec \"\$java\" -jar \"\$dir/../libs/$jarName\" \"\$@\"",
            ).joinToString("\n") + "\n",
            Charsets.UTF_8,
        )
        posix.setExecutable(true)
        // Named .bat rather than .cmd on purpose: the harness routes a .bat through `cmd /c`
        // and launches anything else directly, so this is the Windows spelling of the same
        // seam - and it is what makes the fat-jar tier reproducible on a Windows machine.
        dir.resolve("mkvtool.bat").writeText(
            listOf(
                "@echo off",
                "rem Generated by the jarLauncher Gradle task.",
                "setlocal",
                "if defined JAVA_HOME (set \"JAVA=%JAVA_HOME%\\bin\\java\") else (set \"JAVA=java\")",
                "\"%JAVA%\" -jar \"%~dp0..\\libs\\$jarName\" %*",
                "exit /b %ERRORLEVEL%",
            ).joinToString("\r\n") + "\r\n",
            Charsets.UTF_8,
        )
    }
}

// Native binary verification.
//
// Everything done to a freshly compiled binary — the self-asserting probes, the acceptance suite,
// the one command with no oracle case behind it, the startup measurement — as tasks rather than as
// workflow shell. That knowledge used to exist only as YAML, which cannot be run on a developer
// machine, so local verification and CI verification were two implementations of one idea, free to
// disagree. `nativeLoop` is the whole loop in one command; docs/building.md is how to run it.
//
// One rule holds all of it together: **a task that inspects a binary reads what is on disk, and
// only nativeCompile produces one.** So every task below takes -PnativeBinary and none of them
// depends on nativeCompile. In CI the binary that gets verified has to be the same file
// releaseArchive then packages — not a fresh, therefore untested, compile of the same sources — and
// a binary from somewhere else (a downloaded asset, a copy signed after the fact) has to be
// verifiable too. nativeLoop is the single place the compile and the checks are chained.
//
// Equally deliberate: none of this is wired into `check` or `build`. Those must stay green on a
// machine with no GraalVM, no Groovy and no MKVToolNix, which is every machine that only wants the
// jar.

// Process plumbing, in an object so a task action that reaches for it captures no build-script
// state, and the four tasks share one implementation of "run this and tell me what it said".
object NativeVerify {
    /**
     * Runs a command, echoing its merged output line by line as it arrives, and returns the exit
     * code alongside those lines.
     *
     * Streaming is not a nicety: the acceptance suite runs for minutes, and `inheritIO()` would
     * hand the child the Gradle daemon's own stdout, where nothing ever displays it.
     */
    fun run(
        command: List<String>,
        workingDir: File,
        env: Map<String, String>,
        echo: (String) -> Unit,
    ): Pair<Int, List<String>> {
        val builder = ProcessBuilder(command)
            .directory(workingDir)
            // One stream, drained on this thread. Two undrained streams is how a chatty child fills
            // a pipe buffer and blocks forever.
            .redirectErrorStream(true)
        builder.environment().putAll(env)
        val process = try {
            builder.start()
        } catch (e: IOException) {
            throw GradleException("could not run ${command.first()}: ${e.message}")
        }
        val lines = mutableListOf<String>()
        process.inputStream.bufferedReader().forEachLine { line ->
            lines += line
            echo(line)
        }
        return process.waitFor() to lines
    }

    /** Whether a command starts and exits 0 — i.e. the tool is present and runnable. */
    fun isRunnable(command: List<String>): Boolean = try {
        ProcessBuilder(command)
            .redirectErrorStream(true)
            .redirectOutput(ProcessBuilder.Redirect.DISCARD)
            .start()
            .waitFor() == 0
    } catch (e: IOException) {
        false
    }

    /**
     * One timed `--version`, in nanoseconds.
     *
     * The exit code is checked, unlike the shell version this replaces: a `--version` that had
     * started failing would exit almost instantly and sail under any ceiling, so the measurement
     * would report an improvement.
     */
    fun timeVersion(binary: File): Long {
        val started = System.nanoTime()
        val code = ProcessBuilder(binary.absolutePath, "--version")
            .redirectErrorStream(true)
            .redirectOutput(ProcessBuilder.Redirect.DISCARD)
            .start()
            .waitFor()
        val elapsed = System.nanoTime() - started
        require(code == 0) { "`mkvtool --version` exited $code during the startup measurement" }
        return elapsed
    }

    /** Formatted to one decimal under a fixed locale, so a comma never arrives where a point is expected. */
    fun millis(nanos: Long): String = String.format(Locale.ROOT, "%.1f", nanos / 1_000_000.0)

    fun meanMillis(nanos: List<Long>): Double = nanos.sum() / 1_000_000.0 / nanos.size
}

// The frozen harness resolves its own paths from its script location, so it can be launched from
// anywhere; the binary and mkvmerge overrides, however, are resolved against the working directory,
// which is why every invocation below runs in the project directory and passes absolute paths.
val harnessScript = "src/test/run_tests.groovy"

/**
 * Windows cannot start a script directly — `CreateProcess` runs executables, so a `.bat` or an
 * extension-less shell script needs an interpreter in front of it. Groovy ships as `groovy.bat`
 * there, and the CI legs name a `bin/groovy` shell script, so both forms turn up. The harness solves
 * the same problem the same way for the binary it launches.
 */
fun launcherFor(command: String): List<String> =
    if (hostIsWindows && !command.lowercase().endsWith(".exe")) listOf("cmd", "/c", command) else listOf(command)

// The acceptance suite keys its scratch directories by case name and recreates them at case start,
// so two concurrent runs delete each other's fixtures mid-test and the failure surfaces somewhere
// unrelated. That used to be a rule people remembered; it is now a lock, because the container makes
// it easy to start a second run without noticing (two `docker compose run` invocations share the
// scratch volume). The lock file lives in the scratch directory on purpose: that is the shared
// storage, and it is a real filesystem rather than a bind mount, where advisory locks are unreliable.
//
// No in-build guard beside it: this is a single-project build with no intra-project task
// parallelism, so Gradle cannot run two of these at once by itself.
val acceptanceWorkDir = layout.projectDirectory.dir("src/test/work").asFile

val projectDirFile: File = layout.projectDirectory.asFile

// -PnativeBinary may name a path anywhere; the default is relative to the project.
val nativeBinaryFile: File = File(nativeBinaryPath).let {
    if (it.isAbsolute) it else File(projectDirFile, nativeBinaryPath)
}

// First hit wins. $GROOVY is what the native workflow already exports for its harness steps, so
// pointing those legs at these tasks needs no change there.
val groovyBin: String = providers.gradleProperty("groovyBin")
    .orElse(providers.environmentVariable("GROOVY"))
    .getOrElse("groovy")

// Passed straight through to the harness, which also writes it into every config.yaml it generates.
val mkvmergeExeOverride: String? = providers.gradleProperty("mkvmergeExe").orNull

val acceptanceFilter: String? = providers.gradleProperty("filter").orNull

val startupRuns: Int = providers.gradleProperty("startupRuns").map(String::toInt).getOrElse(50)
val startupCeilingMs: Int = providers.gradleProperty("startupCeilingMs").map(String::toInt).getOrElse(200)

// Which acceptance pass nativeCheck includes. The native workflow's matrix already carries exactly
// this distinction per leg, so it maps onto one property rather than onto separate task names.
val acceptanceMode: String = providers.gradleProperty("acceptance").getOrElse("full")
require(acceptanceMode in setOf("full", "smoke", "none")) {
    "-Pacceptance must be full, smoke or none (got '$acceptanceMode')"
}

// One representative case per command, rather than the whole suite. This subset exists to catch what
// differs *per platform* in a native image, which is a different question from whether the tool is
// correct — and the full suite on every platform would triple the cost for coverage one platform
// already provides. Each case earns its place:
val smokeCases = listOf(
    // to-utf8: a windows-1251 decode through the CLI, i.e. -H:+AddAllCharsets with teeth.
    "50_to_utf8_converts_in_place",
    // fix-srt: the reformat state machine over a charset-detected read.
    "87_fix_srt_fixes_valid_file",
    // propedit: real mkvpropedit argv passthrough (31 is a no-op, so it proves less). This is the only
    // case here that runs mkvpropedit, so it carries that tool's whole native coverage.
    "32_propedit_passthrough",
    // fetch-episodes: loopback HTTP, both metadata files written.
    "35_fetch_episodes_stub",
    // rename: the episodes.yaml load, i.e. snakeyaml in the image.
    "94_rename_prefers_yaml",
    // inspect: both modes off one mkvmerge -J scan.
    "74_check_and_identify_combined",
    // mux: a real mkvmerge invocation end to end.
    "01_one_audio_one_subtitle",
    // Cyrillic through fetch, rename and file names — where a native image's stdout and filesystem
    // encodings would differ from the JVM's if they differ anywhere.
    "38_non_ascii_titles_round_trip",
)

// Refuse rather than skip, and name the fix. The project's skip discipline is about individual
// cases whose prerequisites are missing (mkvpropedit, a TheMovieDB key); a whole tier that quietly
// did not run is the one outcome worse than a red one.
fun requireHarnessTools(groovy: String) {
    require(NativeVerify.isRunnable(launcherFor(groovy) + "--version")) {
        "groovy not found at '$groovy' - tried -PgroovyBin, then \$GROOVY, then PATH. " +
            "The acceptance suite cannot run without it; see docs/building.md."
    }
    val mkvmerge = mkvmergeExeOverride ?: "mkvmerge"
    require(NativeVerify.isRunnable(launcherFor(mkvmerge) + "--version")) {
        "mkvmerge not found at '$mkvmerge' - put MKVToolNix on PATH or pass -PmkvmergeExe=<path>. " +
            "The acceptance suite needs it at startup and asserts through it; see docs/building.md."
    }
}

// The wording is releaseArchive's, deliberately: the same mistake produces the same sentence
// wherever it is made.
fun requireNativeBinary(binary: File) {
    require(binary.isFile) {
        "no native binary at $binary - run nativeCompile first, or pass -PnativeBinary=<path>"
    }
}

/** Holds the acceptance scratch directory for the duration of a suite run, or refuses to start. */
fun <T> withAcceptanceLock(workDir: File, body: () -> T): T {
    workDir.mkdirs()
    val lockFile = File(workDir, ".lock")
    RandomAccessFile(lockFile, "rw").use { file ->
        val lock = file.channel.tryLock()
            ?: throw GradleException(
                "another acceptance run holds $workDir - the suite keys its scratch directories by " +
                    "case name, so two runs would delete each other's fixtures mid-test",
            )
        lock.use { return body() }
    }
}

/** Runs the harness once and returns its output lines, failing on a non-zero exit. */
fun runHarness(
    binary: File,
    groovy: String,
    filter: String?,
    echo: (String) -> Unit,
): Pair<Int, List<String>> {
    val command = buildList {
        addAll(launcherFor(groovy))
        add(harnessScript)
        add("--app-bin")
        add(binary.absolutePath)
        mkvmergeExeOverride?.let { add("--mkvmerge-exe"); add(it) }
        filter?.let { add("--filter"); add(it) }
    }
    // NO_COLOR so the assertions below read plain text whether or not a terminal is attached.
    return NativeVerify.run(command, projectDirFile, mapOf("NO_COLOR" to "1"), echo)
}

/**
 * The suite's own verdict, plus the one it cannot give: a filter matching no case runs nothing,
 * prints `0 passed, 0 failed` and exits 0, so a renamed case would leave a green run that tested
 * nothing at all.
 */
fun requireCasesRan(exitCode: Int, lines: List<String>) {
    val summary = lines.lastOrNull { it.matches(Regex("""\d+ passed, \d+ failed""")) }
        ?: throw GradleException("the acceptance suite printed no summary line - it did not finish")
    require(exitCode == 0) { "the acceptance suite reported $summary" }
    val passed = summary.substringBefore(" passed").toInt()
    require(passed > 0) {
        "the acceptance suite ran no cases at all ($summary) - check the -Pfilter value"
    }
}

val nativeCompileTask = tasks.named("nativeCompile")

// dependsOn declares no ordering, so nativeLoop needs this said explicitly; on any invocation
// without nativeCompile in the graph it is simply inert.
fun Task.afterNativeCompile() {
    mustRunAfter(nativeCompileTask)
    // Nothing here produces a file, and every run has to actually run.
    outputs.upToDateWhen { false }
    group = "verification"
}

val nativeSmoke = tasks.register("nativeSmoke") {
    description = "Runs the native binary's built-in probes: charsets, locales, JSON, YAML, HTTPS."
    afterNativeCompile()
    val binary = nativeBinaryFile
    val dir = projectDirFile
    doLast {
        requireNativeBinary(binary)
        // The probes self-assert and exit non-zero on any mismatch, so running them is the assertion.
        val (code, _) = NativeVerify.run(
            listOf(binary.absolutePath, "native-smoke"),
            dir,
            emptyMap(),
        ) { logger.lifecycle(it) }
        require(code == 0) { "native-smoke exited $code" }
    }
}

val unusedFontsCheck = tasks.register("unusedFontsCheck") {
    description = "End-to-end check of find-unused-fonts, the one command no acceptance case covers."
    afterNativeCompile()
    val binary = nativeBinaryFile
    val stagingDir = layout.buildDirectory.dir("font-check")
    doLast {
        requireNativeBinary(binary)
        val staging = stagingDir.get().asFile
        staging.deleteRecursively()
        staging.resolve("fonts").mkdirs()
        staging.resolve("subs.ass").writeText("Style: Default,Cuprum,20\n", Charsets.UTF_8)
        staging.resolve("fonts/Cuprum.ttf").writeText("", Charsets.UTF_8)
        staging.resolve("fonts/Unused Font.otf").writeText("", Charsets.UTF_8)
        val (code, lines) = NativeVerify.run(
            listOf(binary.absolutePath, "find-unused-fonts"),
            staging,
            emptyMap(),
        ) { logger.lifecycle(it) }
        require(code == 0) { "find-unused-fonts exited $code" }
        // One font the subtitle references, one it does not, and the unreferenced base name - no
        // extension, no prefix, no summary - is the whole of the output.
        require(lines == listOf("Unused Font")) {
            "find-unused-fonts reported $lines, expected exactly [Unused Font]"
        }
    }
}

val acceptanceTest = tasks.register("acceptanceTest") {
    description = "Runs the acceptance suite against the native binary. -Pfilter=<substring> narrows it."
    afterNativeCompile()
    val binary = nativeBinaryFile
    val groovy = groovyBin
    val filter = acceptanceFilter
    val workDir = acceptanceWorkDir
    doLast {
        requireNativeBinary(binary)
        requireHarnessTools(groovy)
        val started = System.nanoTime()
        withAcceptanceLock(workDir) {
            val (code, lines) = runHarness(binary, groovy, filter) { logger.lifecycle(it) }
            requireCasesRan(code, lines)
        }
        logger.lifecycle("acceptance suite: ${NativeVerify.millis(System.nanoTime() - started)} ms")
    }
}

val acceptanceSmoke = tasks.register("acceptanceSmoke") {
    description = "Runs one representative acceptance case per command against the native binary."
    afterNativeCompile()
    val binary = nativeBinaryFile
    val groovy = groovyBin
    val cases = smokeCases
    val workDir = acceptanceWorkDir
    doLast {
        requireNativeBinary(binary)
        requireHarnessTools(groovy)
        // --filter takes a single substring, so each case is its own harness run. All of them run
        // before the task fails, because which command broke is the whole answer.
        val onCi = System.getenv("GITHUB_ACTIONS") != null
        val failed = mutableListOf<String>()
        withAcceptanceLock(workDir) {
            cases.forEach { case ->
                logger.lifecycle(if (onCi) "::group::$case" else "--- $case")
                val (code, lines) = runHarness(binary, groovy, case) { logger.lifecycle(it) }
                if (onCi) logger.lifecycle("::endgroup::")
                // A case that self-skips still prints [PASS], so this asserts the case exists and
                // was reached - not merely that the run was green.
                if (code != 0 || lines.none { it == "[PASS] $case" }) failed += case
            }
        }
        require(failed.isEmpty()) { "acceptance cases failed or did not run: ${failed.joinToString(" ")}" }
    }
}

val startupCheck = tasks.register("startupCheck") {
    description = "Measures `mkvtool --version` startup and asserts it against a ceiling."
    afterNativeCompile()
    val binary = nativeBinaryFile
    val runs = startupRuns
    val ceiling = startupCeilingMs
    // Lazy by design, so a host with no release label still runs ordinary builds; reading it inside
    // this block keeps that.
    val label = { releasePlatform }
    doLast {
        requireNativeBinary(binary)
        // Why the tool is compiled at all: the scripts it replaces took about four seconds to print
        // a help screen. Not a cold start in the strict sense - by the time this runs the binary has
        // been executed already, so it is page-cached; what is measured is the first run and the
        // steady state over many.
        val first = NativeVerify.timeVersion(binary)
        val mean = NativeVerify.meanMillis(List(runs) { NativeVerify.timeVersion(binary) })
        val meanText = String.format(Locale.ROOT, "%.1f", mean)
        val firstText = NativeVerify.millis(first)
        logger.lifecycle("startup ${label()}: first --version $firstText ms, mean of $runs $meanText ms")
        // Read at execution time, so nothing about the task's configuration depends on where it runs.
        System.getenv("GITHUB_STEP_SUMMARY")?.let { path ->
            File(path).appendText(
                listOf(
                    "### Startup: ${label()}",
                    "",
                    "- first `--version`: $firstText ms",
                    "- mean of $runs runs: $meanText ms",
                    "",
                ).joinToString("\n"),
                Charsets.UTF_8,
            )
        }
        // Asserted rather than merely recorded, so a regression cannot pass silently.
        require(mean <= ceiling) {
            "startup ceiling exceeded: $meanText ms mean against a $ceiling ms ceiling"
        }
    }
}

// Cheapest and highest-signal first: the probes catch a dropped native-image flag in milliseconds
// rather than eight minutes into a suite. Startup runs last, when the binary is warm on disk, which
// is what the number is meant to describe. mustRunAfter only orders tasks that are both in the
// graph, so naming both acceptance passes here costs nothing when only one of them runs.
unusedFontsCheck { mustRunAfter(nativeSmoke) }
acceptanceTest { mustRunAfter(unusedFontsCheck) }
acceptanceSmoke { mustRunAfter(unusedFontsCheck) }
startupCheck { mustRunAfter(unusedFontsCheck, acceptanceTest, acceptanceSmoke) }

val nativeCheck = tasks.register("nativeCheck") {
    group = "verification"
    description = "Verifies an existing native binary: probes, fonts, acceptance (-Pacceptance=full|smoke|none), startup."
    dependsOn(nativeSmoke, unusedFontsCheck, startupCheck)
    when (acceptanceMode) {
        "full" -> dependsOn(acceptanceTest)
        "smoke" -> dependsOn(acceptanceSmoke)
    }
}

tasks.register("nativeLoop") {
    group = "verification"
    description = "The whole loop: compile the native binary, then verify it."
    dependsOn(nativeCompileTask, nativeCheck)
}
