// mkvtool v2 build. Versions come from gradle.properties (single source of truth).

plugins {
    // Versions supplied by pluginManagement in settings.gradle.kts.
    kotlin("jvm")
    // kapt runs picocli-codegen: it is a javac annotation processor, so KSP cannot
    // run it. picocli-codegen generates the GraalVM reflection config under
    // META-INF/native-image, consumed by the native-image build below.
    kotlin("kapt")
    // kotlinx.serialization is a *compiler* plugin: it generates each @Serializable
    // class's serializer at compile time, so JSON parsing needs no runtime reflection
    // and therefore no native-image reachability config.
    kotlin("plugin.serialization")
    // installDist provides the dev launcher; also names it via applicationName below.
    application
    // Maintained shadow fork (com.gradleup.*); the old johnrengelman fork is dead.
    // Wires shadowJar into `assemble`, so `build` produces the fat jar.
    id("com.gradleup.shadow")
    // GraalVM native-image. Adds the `nativeCompile` task and consumes the reflection
    // config kapt/picocli-codegen emits under META-INF/native-image. Applying it costs
    // nothing on an ordinary JDK; only `nativeCompile` requires a GraalVM JDK.
    id("org.graalvm.buildtools.native")
}

group = "org.plukh"
// version is inherited from gradle.properties.

val picocliVersion = providers.gradleProperty("picocliVersion").get()
val kotestVersion = providers.gradleProperty("kotestVersion").get()
val snakeyamlVersion = providers.gradleProperty("snakeyamlVersion").get()
val kotlinxSerializationVersion = providers.gradleProperty("kotlinxSerializationVersion").get()

// JDK 21 (LTS) toolchain via Gradle toolchains — compilation and test execution use
// JDK 21 regardless of the JDK that launched Gradle.
kotlin {
    jvmToolchain(21)
}

application {
    mainClass.set("org.plukh.mkvtool.cli.MainKt")
    // Makes the installDist / distribution launcher be named `mkvtool` (+ .bat).
    applicationName = "mkvtool"
}

dependencies {
    implementation("info.picocli:picocli:$picocliVersion")
    kapt("info.picocli:picocli-codegen:$picocliVersion")
    implementation("org.yaml:snakeyaml:$snakeyamlVersion")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:$kotlinxSerializationVersion")

    testImplementation("io.kotest:kotest-runner-junit5:$kotestVersion")
    testImplementation("io.kotest:kotest-assertions-core:$kotestVersion")
}

// Version is defined once (project.version, from gradle.properties) and surfaced to
// the runtime through a generated Kotlin source. A compiled-in `const` needs no
// classpath resource loading, so it behaves identically under installDist, the shadow
// jar, and native-image with zero resource-inclusion config — unlike a bundled
// .properties resource, which native-image would need told about explicitly.
val generateBuildInfo = tasks.register("generateBuildInfo") {
    val version = project.version.toString()
    val outputDir = layout.buildDirectory.dir("generated/buildinfo")
    inputs.property("version", version)
    outputs.dir(outputDir)
    doLast {
        val pkgDir = outputDir.get().asFile.resolve("org/plukh/mkvtool")
        pkgDir.mkdirs()
        pkgDir.resolve("BuildInfo.kt").writeText(
            """
            package org.plukh.mkvtool

            /** Build-time facts, generated by the `generateBuildInfo` Gradle task. */
            internal object BuildInfo {
                const val VERSION: String = "$version"
            }
            """.trimIndent() + "\n",
            Charsets.UTF_8,
        )
    }
}

// Passing the task provider to srcDir wires both the generated directory and the
// compileKotlin -> generateBuildInfo dependency.
kotlin.sourceSets.main {
    kotlin.srcDir(generateBuildInfo)
}

// Native binary. The two buildArgs guard the two silent native-image failure modes;
// the hidden `native-smoke` command probes both end-to-end in CI, and would fail at
// runtime if either flag were dropped:
//   -H:+AddAllCharsets  - keep every JDK charset; without it `to-utf8` loses non-default
//                         encodings (e.g. windows-1251) and Charset.forName throws.
//   -H:+IncludeAllLocales - bundle CLDR locale data; without it language display names
//                           (Русский, 日本語) come back empty.
graalvmNative {
    // Our only reachability config comes from picocli-codegen (emitted under
    // META-INF/native-image). The plugin's third-party GraalVM reachability-metadata
    // repository is unused here, and its schema demands a newer GraalVM than the last
    // GraalVM CE for JDK 21 (21.0.2, which CI's graalvm-community/21 also resolves to)
    // ships - leaving it on fails nativeCompile. Disable it.
    metadataRepository {
        enabled.set(false)
    }
    binaries {
        named("main") {
            imageName.set("mkvtool")
            mainClass.set(application.mainClass.get())
            buildArgs.add("-H:+AddAllCharsets")
            buildArgs.add("-H:+IncludeAllLocales")
            // kotlinx.serialization initializes its generated serializers at build time, which reaches
            // kotlin.DeprecationLevel (the enum behind every @Deprecated annotation) and leaves it
            // initialized while native-image's default policy still wants it at run time — the build then
            // fails outright. Marking the enum build-time settles the disagreement; it is a compile-time
            // constant holder with no state worth deferring. Without this, nativeCompile fails as soon as
            // anything @Serializable is reachable.
            buildArgs.add("--initialize-at-build-time=kotlin.DeprecationLevel")
        }
    }
}

tasks.test {
    useJUnitPlatform()
}

tasks.jar {
    manifest {
        attributes("Implementation-Version" to project.version)
    }
}

tasks.shadowJar {
    // Make the fat jar runnable via `java -jar`.
    manifest {
        attributes("Main-Class" to application.mainClass.get())
    }
}
